### ISSUE TITLE
Creating a PubSub object with fallback enabled doesn't give a great error on attempted streaming pull

### ISSUE THREAD

**Issue by feywind** [googleapis/nodejs-pubsub#1145]
```
TypeError: serviceStub[methodName].apply is not a function or its return value is not iterable

at Service.newServiceStub.(anonymous function) [as streamingPull] (node_modules\@google-cloud\pubsub\node_modules\google-gax\src\fallback.ts:261:11)

at MessageStream._fillStreamPool (node_modules\@google-cloud\pubsub\src\message-stream.ts:234:41)

at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

There is some belief that a newer gax version already gives a better error message for this, but it should be tested.

**Comment by meredithslota** [comment]
There's some additional context for this issue in b/160672356 (which is now closed but may be useful in tackling this one).

**Comment by feywind** [comment]
I'm just going to close this as part of our cleanup.
