### ISSUE TITLE
Topic.flush() throws error

### ISSUE THREAD

**Issue by rhodgkins** [googleapis/nodejs-pubsub#1178]
#### Environment details

  - OS: mac
  - Node.js version: 14.15.4
  - `@google-cloud/pubsub` version: 2.7.0

#### Steps to reproduce

```js
const { PubSub } = require('@google-cloud/pubsub')
const pubsub = new PubSub()
const topic = pubsub.topic('blah')
topic.flush().then(() => console.log('Flushed'), err => console.error('Error:', err))
```

Throws the following error:

```
> (node:5485) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'batch' of undefined
    at publish (<path>/node_modules/@google-cloud/pubsub/build/src/publisher/message-queues.js:99:46)
    at <path>/node_modules/@google-cloud/promisify/build/src/index.js:57:28
    at new Promise (<anonymous>)
    at wrapper (<path>/node_modules/@google-cloud/promisify/build/src/index.js:42:16)
    at Publisher.flush (<path>/node_modules/@google-cloud/pubsub/build/src/publisher/index.js:73:69)
    at Publisher.wrapper (<path>/node_modules/@google-cloud/promisify/build/src/index.js:30:35)
    at Topic.flush (<path>/node_modules/@google-cloud/pubsub/build/src/topic.js:116:24)
    at <path>/node_modules/@google-cloud/promisify/build/src/index.js:57:28
    at new Promise (<anonymous>)
    at Topic.wrapper (<path>/node_modules/@google-cloud/promisify/build/src/index.js:42:16)
```

I think the promisify need to use `.bind` to the queue:

https://github.com/googleapis/nodejs-pubsub/blob/cf3f31f70156a450054428aa1054e641af0d6531/src/publisher/index.ts#L105-L108

So should be (just a guess):

```ts
 const publishes = [promisify(this.queue.publish).bind(this.queue)()]; 
 Array.from(this.orderedQueues.values()).forEach(q => 
   publishes.push(promisify(q.publish).bind(q)()) 
 ); 
```

**Comment by feywind** [comment]
@rhodgkins Thanks for the report and the detailed analysis! I think you're probably right there.
