### ISSUE TITLE
Error when deleting subscription just before closing the client

### ISSUE THREAD

**Issue by noe-charmet** [googleapis/nodejs-pubsub#1323]
After a recent update (can't same from which version it was unfortunately). We have started seeing errors in our logs coming from this client, when deleting a subscription just before closing the client.

# Environment details

  - OS: Linux (Alpine)
  - Node.js version: 16
  - npm version: 7.11.2
  - `@google-cloud/pubsub` version:  2.13.0

# Steps to reproduce

```javascript
const client = new PubSub({
  projectId: // Project ID,
  autoRetry: true,
});
const topic = 'MyTopic';
const subscriptionName = 'MySubscription'
const subscription = client.topic(topic).subscription(subscriptionName);
const [subscriptionInstance] = await subscription.get({autoCreate: true});
await this.subscriptionInstance.delete();
await client.close();
```
# Error

```
Cannot use a closed PubSub object.
    at PubSub.request (/rolo/node_modules/@google-cloud/pubsub/src/pubsub.ts:1267:19)
    at Subscription.delete (/rolo/node_modules/@google-cloud/pubsub/src/subscription.ts:560:10)
    at /rolo/node_modules/@google-cloud/promisify/build/src/index.js:57:28
    at new Promise (<anonymous>)
    at Subscription.wrapper (/rolo/node_modules/@google-cloud/promisify/build/src/index.js:42:16)
    at Subscriber.shutdown (/rolo/node_modules/@rolo-chat/server-engine/src/entities/Subscriber/Subscriber.js:106:15)
    at callback (/rolo/node_modules/@rolo-chat/server-engine/src/entities/Server/Server.js:194:46)
    at Array.map (<anonymous>)
    at Server.<anonymous> (/rolo/node_modules/@rolo-chat/server-engine/src/entities/Server/Server.js:193:34)
    at Server.emit (node:events:406:35)
    at Server.incomingRequest (/rolo/node_modules/@opentelemetry/plugin-http/src/http.ts:279:25)
    at emitCloseNT (node:net:1648:8)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Could it be linked to the fact that we are also using open telemetry in our stack. Could this cause some kind of conflict?

**Comment by feywind** [comment]
@noe-charmet I don't think it would be the OpenTelemetry, unless that just happens to delay the processing of outstanding promises, and triggers a race condition, or something like that. There's this comment on `client.close()`:

```
   * Closes out this object, releasing any server connections. Note that once
   * you close a PubSub object, it may not be used again. Any pending operations
   * (e.g. queued publish messages) will fail. If you have topic or subscription
   * objects that may have pending operations, you should call close() on those
   * first if you want any pending messages to be delivered correctly. The
   * PubSub class doesn't track those.
```

Sadly there isn't a thing to track when you're doing a delete operation on the `client` itself, which seems like a bit of an oversight.

Vaguely related request: https://github.com/googleapis/nodejs-pubsub/issues/725 (more deterministic shutdown)

**Comment by feywind** [comment]
Moving this to the internal backlog alongside 725.
