### ISSUE TITLE
Can't install @google-cloud/pubsub

### ISSUE THREAD

**Issue by ftechiesnitin** [googleapis/nodejs-pubsub#134]
Hello Guys,

I am trying to install ``` npm install --save @google-cloud/pubsub ```, but I am facing following issue,

![screen shot 2018-05-30 at 11 13 47 am](https://user-images.githubusercontent.com/11813973/40696906-a05890ec-63fa-11e8-9944-f2b571862ba5.png)
 
I am using,
- OS: MacOS Sierra v 10.12.6
  - Node.js version: v9.4.0
  - npm version: v6.1.0

Here is the log file,
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@google-cloud/pubsub' ]
2 info using npm@6.1.0
3 info using node@v9.4.0
4 verbose npm-session 7428eb86ce998f58
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@google-cloud%2fpubsub 885ms (from cache)
8 silly pacote tag manifest for @google-cloud/pubsub@latest fetched in 916ms
9 timing stage:loadCurrentTree Completed in 1384ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 92ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule @google-cloud/pubsub@0.18.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/delay 37ms (from cache)
18 silly pacote range manifest for delay@^2.0.0 fetched in 39ms
19 silly resolveWithNewModule delay@2.0.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/arrify 76ms (from cache)
21 http fetch GET 304 https://registry.npmjs.org/google-gax 76ms (from cache)
22 silly pacote range manifest for google-gax@^0.16.0 fetched in 78ms
23 silly resolveWithNewModule google-gax@0.16.1 checking installable status
24 silly pacote range manifest for arrify@^1.0.0 fetched in 80ms
25 silly resolveWithNewModule arrify@1.0.1 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/async-each 82ms (from cache)
27 http fetch GET 304 https://registry.npmjs.org/google-proto-files 81ms (from cache)
28 http fetch GET 304 https://registry.npmjs.org/lodash.chunk 43ms (from cache)
29 http fetch GET 304 https://registry.npmjs.org/is 82ms (from cache)
30 http fetch GET 304 https://registry.npmjs.org/duplexify 84ms (from cache)
31 silly pacote range manifest for async-each@^1.0.1 fetched in 87ms
32 silly resolveWithNewModule async-each@1.0.1 checking installable status
33 silly pacote range manifest for lodash.chunk@^4.2.0 fetched in 48ms
34 silly resolveWithNewModule lodash.chunk@4.2.0 checking installable status
35 silly pacote range manifest for google-proto-files@^0.15.0 fetched in 89ms
36 silly resolveWithNewModule google-proto-files@0.15.1 checking installable status
37 silly pacote range manifest for is@^3.0.1 fetched in 90ms
38 silly resolveWithNewModule is@3.2.1 checking installable status
39 http fetch GET 304 https://registry.npmjs.org/google-auto-auth 91ms (from cache)
40 silly pacote range manifest for duplexify@^3.5.4 fetched in 93ms
41 silly resolveWithNewModule duplexify@3.6.0 checking installable status
42 silly pacote range manifest for google-auto-auth@^0.9.0 fetched in 94ms
43 silly resolveWithNewModule google-auto-auth@0.9.7 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/lodash.snakecase 25ms (from cache)
45 silly pacote range manifest for lodash.snakecase@^4.1.1 fetched in 26ms
46 silly resolveWithNewModule lodash.snakecase@4.1.1 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/lodash.merge 27ms (from cache)
48 silly pacote range manifest for lodash.merge@^4.6.0 fetched in 28ms
49 silly resolveWithNewModule lodash.merge@4.6.1 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/uuid 23ms (from cache)
51 silly pacote range manifest for uuid@^3.1.0 fetched in 24ms
52 silly resolveWithNewModule uuid@3.2.1 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/through2 71ms (from cache)
54 silly pacote range manifest for through2@^2.0.3 fetched in 72ms
55 silly resolveWithNewModule through2@2.0.3 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/extend 302ms (from cache)
57 silly pacote range manifest for extend@^3.0.1 fetched in 304ms
58 silly resolveWithNewModule extend@3.0.1 checking installable status
59 http fetch GET 304 https://registry.npmjs.org/@google-cloud%2fcommon 851ms (from cache)
60 silly pacote range manifest for @google-cloud/common@^0.16.1 fetched in 854ms
61 silly resolveWithNewModule @google-cloud/common@0.16.2 checking installable status
62 http fetch GET 404 https://registry.npmjs.org/protobufjs 859ms
63 silly fetchPackageMetaData error for protobufjs@^6.8.1 404 Not Found: protobufjs@^6.8.1
64 timing stage:rollbackFailedOptional Completed in 1ms
65 timing stage:runTopLevelLifecycles Completed in 2446ms
66 silly saveTree project_name@1.0.0
66 silly saveTree ├─┬ @google-cloud/pubsub@0.18.0
66 silly saveTree │ ├─┬ @google-cloud/common@0.16.2
66 silly saveTree │ │ ├── arrify@1.0.1
66 silly saveTree │ │ ├─┬ duplexify@3.6.0
66 silly saveTree │ │ │ └── inherits@2.0.3
66 silly saveTree │ │ ├── extend@3.0.1
66 silly saveTree │ │ ├─┬ google-auto-auth@0.9.7
66 silly saveTree │ │ │ └─┬ async@2.6.1
66 silly saveTree │ │ │   └── lodash@4.17.10
66 silly saveTree │ │ ├── is@3.2.1
66 silly saveTree │ │ └── through2@2.0.3
66 silly saveTree │ ├── arrify@1.0.1
66 silly saveTree │ ├── async-each@1.0.1
66 silly saveTree │ ├── delay@2.0.0
66 silly saveTree │ ├── duplexify@3.6.0
66 silly saveTree │ ├── extend@3.0.1
66 silly saveTree │ ├── google-auto-auth@0.9.7
66 silly saveTree │ ├─┬ google-gax@0.16.1
66 silly saveTree │ │ └── google-proto-files@0.15.1
66 silly saveTree │ ├── google-proto-files@0.15.1
66 silly saveTree │ ├── is@3.2.1
66 silly saveTree │ ├── lodash.chunk@4.2.0
66 silly saveTree │ ├── lodash.merge@4.6.1
66 silly saveTree │ ├── lodash.snakecase@4.1.1
66 silly saveTree │ ├── through2@2.0.3
66 silly saveTree │ └── uuid@3.2.1
66 silly saveTree ├─┬ body-parser@1.18.3
66 silly saveTree │ ├── bytes@3.0.0
66 silly saveTree │ ├── content-type@1.0.4
66 silly saveTree │ ├─┬ debug@2.6.9
66 silly saveTree │ │ └── ms@2.0.0
66 silly saveTree │ ├── depd@1.1.2
66 silly saveTree │ ├─┬ http-errors@1.6.3
66 silly saveTree │ │ ├── setprototypeof@1.1.0
66 silly saveTree │ │ └── statuses@1.4.0
66 silly saveTree │ ├─┬ iconv-lite@0.4.23
66 silly saveTree │ │ └── safer-buffer@2.1.2
66 silly saveTree │ ├─┬ on-finished@2.3.0
66 silly saveTree │ │ └── ee-first@1.1.1
66 silly saveTree │ ├── qs@6.5.2
66 silly saveTree │ ├─┬ raw-body@2.3.3
66 silly saveTree │ │ └── unpipe@1.0.0
66 silly saveTree │ └─┬ type-is@1.6.16
66 silly saveTree │   ├── media-typer@0.3.0
66 silly saveTree │   └─┬ mime-types@2.1.18
66 silly saveTree │     └── mime-db@1.33.0
66 silly saveTree ├─┬ express@4.16.3
66 silly saveTree │ ├─┬ accepts@1.3.5
66 silly saveTree │ │ └── negotiator@0.6.1
66 silly saveTree │ ├── array-flatten@1.1.1
66 silly saveTree │ ├─┬ body-parser@1.18.2
66 silly saveTree │ │ ├── iconv-lite@0.4.19
66 silly saveTree │ │ ├── qs@6.5.1
66 silly saveTree │ │ └─┬ raw-body@2.3.2
66 silly saveTree │ │   └─┬ http-errors@1.6.2
66 silly saveTree │ │     ├── depd@1.1.1
66 silly saveTree │ │     └── setprototypeof@1.0.3
66 silly saveTree │ ├── content-disposition@0.5.2
66 silly saveTree │ ├── cookie-signature@1.0.6
66 silly saveTree │ ├── cookie@0.3.1
66 silly saveTree │ ├── encodeurl@1.0.2
66 silly saveTree │ ├── escape-html@1.0.3
66 silly saveTree │ ├── etag@1.8.1
66 silly saveTree │ ├─┬ finalhandler@1.1.1
66 silly saveTree │ │ └── parseurl@1.3.2
66 silly saveTree │ ├── fresh@0.5.2
66 silly saveTree │ ├── merge-descriptors@1.0.1
66 silly saveTree │ ├── methods@1.1.2
66 silly saveTree │ ├── parseurl@1.3.2
66 silly saveTree │ ├── path-to-regexp@0.1.7
66 silly saveTree │ ├─┬ proxy-addr@2.0.3
66 silly saveTree │ │ ├── forwarded@0.1.2
66 silly saveTree │ │ └── ipaddr.js@1.6.0
66 silly saveTree │ ├── qs@6.5.1
66 silly saveTree │ ├── range-parser@1.2.0
66 silly saveTree │ ├── safe-buffer@5.1.1
66 silly saveTree │ ├─┬ send@0.16.2
66 silly saveTree │ │ ├── destroy@1.0.4
66 silly saveTree │ │ └── mime@1.4.1
66 silly saveTree │ ├── serve-static@1.13.2
66 silly saveTree │ ├── utils-merge@1.0.1
66 silly saveTree │ └── vary@1.1.2
66 silly saveTree ├─┬ socket.io-pubsub@1.1.0
66 silly saveTree │ ├── shortid@2.2.8
66 silly saveTree │ └── socket.io-adapter@1.1.1
66 silly saveTree └─┬ socket.io@2.1.1
66 silly saveTree   ├── debug@3.1.0
66 silly saveTree   ├─┬ engine.io@3.2.0
66 silly saveTree   │ ├── base64id@1.0.0
66 silly saveTree   │ ├── debug@3.1.0
66 silly saveTree   │ ├─┬ engine.io-parser@2.1.2
66 silly saveTree   │ │ ├── after@0.8.2
66 silly saveTree   │ │ ├── arraybuffer.slice@0.0.7
66 silly saveTree   │ │ ├── base64-arraybuffer@0.1.5
66 silly saveTree   │ │ ├── blob@0.0.4
66 silly saveTree   │ │ └─┬ has-binary2@1.0.3
66 silly saveTree   │ │   └── isarray@2.0.1
66 silly saveTree   │ └─┬ ws@3.3.3
66 silly saveTree   │   ├── async-limiter@1.0.0
66 silly saveTree   │   └── ultron@1.1.1
66 silly saveTree   ├── has-binary2@1.0.3
66 silly saveTree   ├─┬ socket.io-client@2.1.1
66 silly saveTree   │ ├── backo2@1.0.2
66 silly saveTree   │ ├── component-bind@1.0.0
66 silly saveTree   │ ├── component-emitter@1.2.1
66 silly saveTree   │ ├── debug@3.1.0
66 silly saveTree   │ ├─┬ engine.io-client@3.2.1
66 silly saveTree   │ │ ├── component-inherit@0.0.3
66 silly saveTree   │ │ ├── debug@3.1.0
66 silly saveTree   │ │ ├── has-cors@1.1.0
66 silly saveTree   │ │ ├── indexof@0.0.1
66 silly saveTree   │ │ ├─┬ parseqs@0.0.5
66 silly saveTree   │ │ │ └─┬ better-assert@1.0.2
66 silly saveTree   │ │ │   └── callsite@1.0.0
66 silly saveTree   │ │ ├── parseuri@0.0.5
66 silly saveTree   │ │ ├── xmlhttprequest-ssl@1.5.5
66 silly saveTree   │ │ └── yeast@0.1.2
66 silly saveTree   │ ├── has-cors@1.1.0
66 silly saveTree   │ ├── indexof@0.0.1
66 silly saveTree   │ ├── object-component@0.0.3
66 silly saveTree   │ ├── parseqs@0.0.5
66 silly saveTree   │ ├── parseuri@0.0.5
66 silly saveTree   │ ├─┬ socket.io-parser@3.2.0
66 silly saveTree   │ │ └── debug@3.1.0
66 silly saveTree   │ └── to-array@0.1.4
66 silly saveTree   └── socket.io-parser@3.2.0
67 verbose stack Error: 404 Not Found: protobufjs@^6.8.1
67 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
67 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
67 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
67 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
67 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
67 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
67 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
67 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
67 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
67 verbose stack     at runCallback (timers.js:756:18)
67 verbose stack     at tryOnImmediate (timers.js:717:5)
67 verbose stack     at processImmediate [as _immediateCallback] (timers.js:697:5)
68 verbose cwd /Users/user_name/Projects/project_name
69 verbose Darwin 16.7.0
70 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "@google-cloud/pubsub"
71 verbose node v9.4.0
72 verbose npm  v6.1.0
73 error code E404
74 error 404 Not Found: protobufjs@^6.8.1
75 verbose exit [ 1, true ]
```

**Comment by jinwoo** [comment]
This seems to be https://github.com/npm/npm/issues/20809. I think npm has been suffering from issues like this recently.

**Comment by walshie4** [comment]
Yeah was getting this exact error yesterday, it's from their recent incident (which appears to still be happening sometimes) https://status.npmjs.org/incidents/238t55n6f03f

**Comment by danoscarmike** [comment]
@ftechiesnitin npmjs.org now reporting this as resolved (updated as of 2 hours ago 20:25UTC).  Can you confirm if it's working for you?

**Comment by ftechiesnitin** [comment]
@danoscarmike thanks, guys. Issue resolved. I can install google-cloud/pubsub now.

**Comment by rdlowrey** [comment]
FWIW, this bug started recurring for me in the past hour.
