### ISSUE TITLE
Error trying to create a topic: Cannot use 'in' operator to search for 'timeout'

### ISSUE THREAD

**Issue by rvillane** [googleapis/nodejs-pubsub#169]
#### Environment details

  - OS:  Darwin Kernel Version 17.6.0
  - Node.js version: 10.0.0
  - npm version: 6.0.1
  - `@google-cloud/pubsub` version: 0.19.0

#### Steps to reproduce

const PubSub = require('@google-cloud/pubsub');
const pubsub = PubSub({
        projectId,
        keyFilename,
});
const topic = pubsub.topic(topicName);
const result = await topic.create(topicName);
 

##### Error message:

[LOCAL] topic topic3 Exist response: false
[LOCAL] topic topic3 doesn't exist - will try to create it
(node:12837) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for 'timeout' in topic3
    at CallSettings.merge (/Users/crmar/GitHub_Storage/event-router-client/node_modules/google-gax/lib/gax.js:200:17)
    at Object.apiCallInner [as createTopic] (/Users/crmar/GitHub_Storage/event-router-client/node_modules/google-gax/lib/api_callable.js:367:33)
    at PublisherClient.createTopic (/Users/crmar/GitHub_Storage/event-router-client/node_modules/@google-cloud/pubsub/src/v1/publisher_client.js:329:32)
    at /Users/crmar/GitHub_Storage/event-router-client/node_modules/@google-cloud/pubsub/src/index.js:836:26
    at PubSub.getClient_ (/Users/crmar/GitHub_Storage/event-router-client/node_modules/@google-cloud/pubsub/src/index.js:810:3)
    at PubSub.request (/Users/crmar/GitHub_Storage/event-router-client/node_modules/@google-cloud/pubsub/src/index.js:827:8)
    at PubSub.createTopic (/Users/crmar/GitHub_Storage/event-router-client/node_modules/@google-cloud/pubsub/src/index.js:312:8)
    at /Users/crmar/GitHub_Storage/event-router-client/node_modules/@google-cloud/common/src/util.js:786:22
    at new Promise (<anonymous>)
    at PubSub.wrapper [as createTopic] (/Users/crmar/GitHub_Storage/event-router-client/node_modules/@google-cloud/common/src/util.js:770:12)
(node:12837) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12837) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

tried explicitly setting the timeout option, but same result:

const result = await topic.create(topicName, { timeout: 200 });

any ideas ?

**Comment by rvillane** [comment]
correct syntax is const result = await pubsub.createTopic(topicName);
