### ISSUE TITLE
 Property 'PublisherClient' does not exist on type

### ISSUE THREAD

**Issue by gaohannk** [googleapis/nodejs-pubsub#610]
I am following the sample code here. https://github.com/googleapis/nodejs-pubsub/blob/master/samples/topics.js

const {v1} = require('@google-cloud/pubsub');

  // Creates a publisher client
  const client = new v1.PublisherClient({
    // optional auth parameters
  });

When I migrate to typescript, I got this error:

src/pubsubclient.ts:7:23 - error TS2339: Property 'PublisherClient' does not exist on type 'typeof import("/Users/hangao/Zume/ingest/node_modules/@google-cloud/pubsub/build/src/index")'.

7 const pubsub = new v1.PublisherClient(credential);
                        ~~~~~~~~~~~~~~~
#### Environment details

  - OS: mac 
  - Node.js version: v8.9.4
  - npm version: 6.9.0
  - `@google-cloud/pubsub` version:     "@google-cloud/pubsub": "^0.28.1",

**Comment by gaohannk** [comment]
If I am using like this:
import pubsub from "@google-cloud/pubsub/";
const pubsubclient = new pubsub.v1.PublisherClient(credential);

the runtime failure is:

onst pubsubclient = new pubsub_1.default.v1.PublisherClient(credential);
                                          ^

TypeError: Cannot read property 'v1' of undefined
    at Object.<anonymous> (/Users/hangao/Zume/ingest/build/src/pubsubclient.js:10:43)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hangao/Zume/ingest/build/src/routes/eventRoutesV1.js:16:40)
    at Module._compile (module.js:643:30)

**Comment by callmehiphop** [comment]
@gaohannk thanks for letting us know about this! I've opened a PR (#611) that I think should fix it. If you want to give it a test run that would be awesome!
