### ISSUE TITLE
Documentation does not match behavior for Duration-based fields

### ISSUE THREAD

**Issue by kamalaboulhosn** [googleapis/nodejs-pubsub#653]
- OS: Mac OS X 10.14.5
  - Node.js version: 11.3.0
  - npm version: 6.4.1
  - `@google-cloud/pubsub` version: .29.1

#### Steps to reproduce

  1. Look at the [documentation for ExpirationPolicy ttl](https://cloud.google.com/nodejs/docs/reference/pubsub/0.28.x/global.html#ExpirationPolicy), which states: A duration in seconds with up to nine fractional digits, terminated by 's'. Example: "3.5s".
  2. Actually try to specify the string as the ttl with code as the following:

```js
    const {PubSub} = require('@google-cloud/pubsub');
    const pubsub = new PubSub();
    const topicName = 'my-existing-topic';
    const subscriptionName = 'my-new-sub';

    const topic = pubsub.topic(topicName);

    const options = {
      expirationPolicy: {
        ttl: "86400s"
      }
    };

    pubsub.topic(topicName).createSubscription(subscriptionName, options);
```

This will result in an error:

```
    (node:67265) UnhandledPromiseRejectionWarning: TypeError: .google.pubsub.v1.ExpirationPolicy.ttl: object expected
    at Type.ExpirationPolicy$fromObject [as fromObject] (eval at Codegen (/Users/aboulhosn/stack-overflow-experiments/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:9:9)
    at Type.fromObject (/Users/aboulhosn/stack-overflow-experiments/node_modules/protobufjs/src/type.js:538:25)
    at Type.Subscription$fromObject [as fromObject] (eval at Codegen (/Users/aboulhosn/stack-overflow-experiments/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:43:31)
    at Type.fromObject (/Users/aboulhosn/stack-overflow-experiments/node_modules/protobufjs/src/type.js:538:25)
    at serialize (/Users/aboulhosn/stack-overflow-experiments/node_modules/@grpc/proto-loader/build/src/index.js:71:27)
    at Object.final_requester.sendMessage (/Users/aboulhosn/stack-overflow-experiments/node_modules/grpc/src/client_interceptors.js:806:37)
    at InterceptingCall._callNext (/Users/aboulhosn/stack-overflow-experiments/node_modules/grpc/src/client_interceptors.js:419:43)
    at InterceptingCall.sendMessage (/Users/aboulhosn/stack-overflow-experiments/node_modules/grpc/src/client_interceptors.js:464:8)
    at InterceptingCall._callNext (/Users/aboulhosn/stack-overflow-experiments/node_modules/grpc/src/client_interceptors.js:428:12)
    at InterceptingCall.sendMessage (/Users/aboulhosn/stack-overflow-experiments/node_modules/grpc/src/client_interceptors.js:464:8)
```

Instead, one has to create an object for ttl, replacing `options` above with:

```js
const options = {
  expirationPolicy: {
    ttl: {
      seconds: 86400
    }
  }
};
```

Either the documentation should be updated to reflect the fact that this string notation doesn't work or the options should be updated to allow this type of specification. Note that the same issue exists for the messageRetentionDuration property as well.

**Comment by callmehiphop** [comment]
@kamalaboulhosn looks like some old docs from an earlier implementation maybe? It also mentions that this feature is beta, but I don't see any mention of that in the latest proto files. Can you confirm?

**Comment by sduskis** [comment]
@callmehiphop does your PR mean that you found the problem that @kamalaboulhosn mentioned?

**Comment by callmehiphop** [comment]
@sduskis yep! It was just stale documentation, probably changed once that feature left beta.

**Comment by helmut-messerer** [comment]
incompetence squared.
this is still in place.
