### ISSUE TITLE
Cannot subscribe to a topic linked with a GCS bucket

### ISSUE THREAD

**Issue by zerefel** [googleapis/nodejs-pubsub#811]
### Problem description
Using `"@google-cloud/pubsub": "^1.1.5"`, cannot obtain an existing subscription for a GCS bucket, or create a new one.

### Reproduction steps
Here's the reproduction code. A GCS bucket with a Pub/Sub topic and a subscription have already been set up.

```js
const pubsubSubscribe = async params => {
    const topic = pubsub.topic(params.topic);
    const result = await topic.subscription(params.subscription, params.options);
        
    return result;
};

const sub = await pubsubSubscribe({
    topic: 'existing-topic',
    subscription: 'existing-subscription'
});
```

### Environment
 - Docker environment `FROM node:10.16`
 - Node version 10.16
 - `"@grpc/grpc-js": "^0.6.5"`

### Additional context
* The exact same code used to work with a previous version of `@google-cloud/pubsub`, and it stopped working after doing a clean build with docker cache disabled. I tried rolling back `grpc` and `@google-cloud/pubsub` to multiple older versions to no avail. We cannot roll back to a working version because we run into weird incompatibilities between `@google-cloud/pubsub` and the old grpc (pre-`@grpc/grpc-js`).

* Stack trace:
```
cloud_1          | uncaughtException: Failed to parse target storage.googleapis.com:undefined
cloud_1          | Error: Failed to parse target storage.googleapis.com:undefined
cloud_1          |     at Function.getDefaultAuthority (/usr/src/app/node_modules/@grpc/grpc-js/build/src/resolver-dns.js:253:15)
cloud_1          |     at Object.getDefaultAuthority (/usr/src/app/node_modules/@grpc/grpc-js/build/src/resolver.js:73:32)
cloud_1          |     at new ChannelImplementation (/usr/src/app/node_modules/@grpc/grpc-js/build/src/channel.js:85:48)
cloud_1          |     at new Client (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js:37:36)
cloud_1          |     at new ServiceClientImpl (/usr/src/app/node_modules/@grpc/grpc-js/build/src/make-client.js:49:5)
cloud_1          |     at GrpcClient.createStub (/usr/src/app/node_modules/google-gax/build/src/grpc.js:236:22)
cloud_1          |     at process._tickCallback (internal/process/next_tick.js:68:7) {"error":{},"stack":"Error: Failed to parse target storage.googleapis.com:undefined\n    at Function.getDefaultAuthority (/usr/src/app/node_modules/@grpc/grpc-js/build/src/resolver-dns.js:253:15)\n    at Object.getDefaultAuthority (/usr/src/app/node_modules/@grpc/grpc-js/build/src/resolver.js:73:32)\n    at new ChannelImplementation (/usr/src/app/node_modules/@grpc/grpc-js/build/src/channel.js:85:48)\n    at new Client (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js:37:36)\n    at new ServiceClientImpl (/usr/src/app/node_modules/@grpc/grpc-js/build/src/make-client.js:49:5)\n    at GrpcClient.createStub (/usr/src/app/node_modules/google-gax/build/src/grpc.js:236:22)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","exception":true,"date":"Mon Nov 04 2019 16:38:15 GMT+0000 (Coordinated Universal Time)","process":{"pid":92,"uid":0,"gid":0,"cwd":"/usr/src/app","execPath":"/usr/local/bin/node","version":"v10.16.1","argv":["/usr/local/bin/node","/usr/src/app/index.js"],"memoryUsage":{"rss":117981184,"heapTotal":50601984,"heapUsed":39967664,"external":36527191}},"os":{"loadavg":[2.0703125,1.7734375,1.716796875],"uptime":4105},"trace":[{"column":15,"file":"/usr/src/app/node_modules/@grpc/grpc-js/build/src/resolver-dns.js","function":"Function.getDefaultAuthority","line":253,"method":"getDefaultAuthority","native":false},{"column":32,"file":"/usr/src/app/node_modules/@grpc/grpc-js/build/src/resolver.js","function":"Object.getDefaultAuthority","line":73,"method":"getDefaultAuthority","native":false},{"column":48,"file":"/usr/src/app/node_modules/@grpc/grpc-js/build/src/channel.js","function":"new ChannelImplementation","line":85,"method":null,"native":false},{"column":36,"file":"/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js","function":"new Client","line":37,"method":null,"native":false},{"column":5,"file":"/usr/src/app/node_modules/@grpc/grpc-js/build/src/make-client.js","function":"new ServiceClientImpl","line":49,"method":null,"native":false},{"column":22,"file":"/usr/src/app/node_modules/google-gax/build/src/grpc.js","function":"GrpcClient.createStub","line":236,"method":"createStub","native":false},{"column":7,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":68,"method":"_tickCallback","native":false}]}
```

**Comment by zerefel** [comment]
I managed to figure it out in a more isolated context. The problem only appears when `@google-cloud/storage` is initiated before PubSub.
Using `@google-cloud/storage: "^4.1.1"`.

Providing further context as to the setup of the connection.

```js
const { Storage } = require(`@google-cloud/storage`);
const { PubSub } = require(`@google-cloud/pubsub`);

/**
 * Establishes GCP connections.
 * @param {object} settings
 * @param {string} settings.projectId
 * @param {string} settings.clientEmail
 * @param {string} settings.privateKey
 * @param {EventEmitter} mediator
 */
const connect = (settings, mediator) => {
    const gcSettings = {
        projectId: settings.projectId,
        credentials: {
            client_email: settings.clientEmail,
            private_key: settings.privateKey
        }
    };

    // the error reproted in the issue is only 
    // present when Storage is initiated before PubSub
    const storage = new Storage(gcSettings); 
    const pubsub = new PubSub(gcSettings);

    // the following seems to work with no problems
    // const pubsub = new PubSub(gcSettings);
    // const storage = new Storage(gcSettings); 

    mediator.emit('gcloud.ready', {
        storage,
        pubsub
    });
};
```

**Comment by shaibt** [comment]
Same problem here.
Node: 12.13.0
PubSub: 1.1.5
Storage: 4.1.2

If I init PubSub before Storage - no problem (so far)
If I init Storage 1st - same exact problem (and trace) as above:
```
Failed to parse target storage.googleapis.com:undefined Error: Failed to parse target storage.googleapis.com:undefined
    at Function.getDefaultAuthority (/node_modules/@grpc/grpc-js/build/src/resolver-dns.js:253:15)
    at Object.getDefaultAuthority (/node_modules/@grpc/grpc-js/build/src/resolver.js:73:32)
    at new ChannelImplementation (/node_modules/@grpc/grpc-js/build/src/channel.js:85:48)
    at new Client (/node_modules/@grpc/grpc-js/build/src/client.js:37:36)
    at new ServiceClientImpl (/node_modules/@grpc/grpc-js/build/src/make-client.js:49:5)
    at GrpcClient.createStub (/node_modules/google-gax/build/src/grpc.js:236:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

BTW, Firestore client (2.6.0) is inited before both.
Also, just noting: Firestore & Pubsub are pulling in google-gax (1.7.5) which is pulling in  @grpc/grpc-js (0.6.9) while Storage isn't. Read in some other GitHub issues this may be related to the issue.

**Comment by feywind** [comment]
Adding this to my hotlist for some attention soon.

**Comment by feywind** [comment]
@zerefel @shaibt Sorry it's taken so long for someone to get back to you on these.

I just built a small repro case out of the original messages above, and I can't get it to misbehave with the old or new versions of storage and pubsub. However, I noticed this:

```
│ │ ├─┬ @grpc/grpc-js@1.0.4
```

So I went back and pulled in the then-current versions of gax and grpc-js explicitly, expecting that I'd see it then. Sadly, I didn't.

So the unsatisfying answer to my investigations here is that, either I need to get some more info on what in your environment might be causing it, or I'm guessing it was something that was fixed in some downstream library.

Can either of you confirm whether this is still an issue for you?

**Comment by feywind** [comment]
Also posting this here in case it helps avoid a round trip. This is my test case:

```
const { Storage } = require(`@google-cloud/storage`);
const { PubSub } = require(`@google-cloud/pubsub`);

async function listFiles() {
  const storage = new Storage(); 

  const result = await storage.bucket('bucket-name').getFiles();
  console.log(result);
}

async function pubsubSubscribe() {
  const pubsub = new PubSub();

  const topic = pubsub.topic('topic-name');
  const sub = await topic.subscription('sub-name');

  const topicExists = await topic.exists();
  const subExists = await sub.exists();

  const result = [topicExists, subExists];
  console.log(result);
}

async function storageFirst() {
  listFiles();
  pubsubSubscribe();
}

async function pubsubFirst() {
  pubsubSubscribe();
  listFiles();
}

storageFirst();
```

**Comment by feywind** [comment]
I'm going to go ahead and close this for now, but please comment/re-open if there are still issues.
